### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by Nari07** [mzeryck/Weather-Cal#175] opened 2022-07-26 05:56 UTC
Keeps displaying “the certificate for this server is invalid” and the widget will not load properly. Is there a fix to this?

**Comment by herrandersen** [comment] 2022-07-26 10:22
The ssl certificate for „api.sunrise-sunset.org“ expired a few days ago, hence the error message.
Don‘t know how to fix it though

**Comment by herrandersen** [comment] 2022-07-26 10:28
Well you could just look for the „https://api.sunrise-sunset.org“ string in the code and change it to „http://…“ and there you go, but the connection would still not be safe though.

**Comment by mzeryck** [comment] 2022-07-27 21:22
Duplicate of #175. Will probably just switch to OpenWeather since they have a sunrise/sunset API.

**Closed** 2022-07-30 21:12 UTC
Labels: Bug
