### ISSUE TITLE
Error adding photo + older settings being ignored

### ISSUE THREAD

**Issue by d3vcoder** [mzeryck/Weather-Cal#99] opened 2020-12-17 02:04 UTC
I get this error when trying to add a new background photo. No error when adding a solid or gradient background 
![77DE9139-6862-463A-BA89-70D005C4BD63](https://user-images.githubusercontent.com/76139174/102434223-54a21800-3fe2-11eb-9f5f-b784c50e7c4d.jpeg)

**Comment by mzeryck** [comment] 2020-12-17 02:39
@d3vcoder What a weird error! Is iCloud turned on for Scriptable? (Settings app > your name > iCloud > scroll to the Scriptable item)

**Comment by d3vcoder** [comment] 2020-12-17 03:04
Yes iCloud is turned on.

**Comment by icsAT** [comment] 2020-12-17 16:20
@d3vcoder I just discoverd the same thing at my sons mobile after performing an code update. @mzeryck already pointed into the right direction, but you not only have to activate iCloud for scriptable, but you have also to turn on iCloud Drive. But be carefull if you turn on iCloud Drive all your Script's seems to be gone, because Scriptable wants to read them from iCloud Drive now. I did not figure out how to get the the locale ones shown in scriptable with iCloud Drive on. You need to set them up new. What I did was to share them by Scriptable to the notes app and get them back after turning on iCloud drive.

**Comment by d3vcoder** [comment] 2020-12-18 18:39
@icsAT thabks for the tip. Unfortunately my phone completely glitches out when I try to turn on iCloud Drive so I can’t test this. Another issue that just cropped up is the code no longer recognizes any changes to text size and will ignore any changes made

**Comment by icsAT** [comment] 2020-12-19 10:50
@d3vcoder I just added a pull request for the picture problem. Actually it was not an edding, but a reading problem. Your second problem is not related to this. It might more be related to Issue #100.

**Comment by mzeryck** [comment] 2020-12-21 00:58
@d3vcoder Thanks for bringing this up, and thanks @icsAT for your solution. In my own testing, the code worked fine with iCloud turned on or off - but since I use iCloud Drive, I didn't even think about this potential situation.

Regardless, it appears the solution should work - if you Update Code, please let me know if that is correct! And, sorry for the few days away from this project.

**Comment by d3vcoder** [comment] 2020-12-21 01:32
You guys are awesome. Thanks for the fix!

Still however having the issue with text size not displaying properly. The strange thing is it will change if I modify the defaultText font size, but changing any individual items size wont have any effect.

**Comment by icsAT** [comment] 2020-12-21 22:34
@d3vcoder none of the other textsizes are working? Could you name at least one item, where the textsize is not working correctly? Also it would be interesting, if you discover this only if the script runs in the widget or also if you start it from the app.

**Comment by d3vcoder** [comment] 2020-12-22 23:58
@icsAT See attached screenshot. Changing the defaultText will change the size of everything. Changing any individual item from that list won’t do anything.
![Uploading 3253FE77-A6F7-4435-8049-E1F46090BB8A.png…]()

**Comment by icsAT** [comment] 2020-12-23 07:16
@d3vcoder I can't see your screenshot.
I tried a lot, even turning on and off icloud drive, but was not able to reproduce this situation. I thought there might be an issue with reading the preference file in your setup, but found none so far. Very strange to me is, that you say
> changing defaultText will change everything
That means writing and reading to preference file seems to work, else it would stay on the provided defaults.

Is the script keeping your changes in the settings or are they gone if you call the the settings the next time?
Also, could you give me the name of your script, as shown in Scriptable?

**Comment by d3vcoder** [comment] 2020-12-23 14:54
@icsAT ill try again. It keeps the settings, it just doesn’t do anything with them. My script name is Weather cal. 

![2819ACC9-CFFC-4B68-9763-5C1F51478206](https://user-images.githubusercontent.com/76139174/103009427-c4ddfb80-4504-11eb-848d-71a0ceba1258.png)

**Comment by icsAT** [comment] 2020-12-23 15:06
@d3vcoder thanks for your information. Could you please run this script [https://pastebin.com/czjFJnEW](https://pastebin.com/czjFJnEW) from Scriptable and post a screenshot of the output.

**Comment by d3vcoder** [comment] 2020-12-23 15:09
@icsAT Here you go. 

![705E63BE-8A86-4734-BBF7-E14D50C89910](https://user-images.githubusercontent.com/76139174/103010808-e3dd8d00-4506-11eb-852c-031b79fe9d8b.png)

**Comment by icsAT** [comment] 2020-12-23 15:17
@d3vcoder that helps I think. The Testscript did not found the preference file. So, maybe also the Weather Cal Script is not finding it for reading the preferences. But and this is not clear to me at moment, it must be somewhere if it stores and shows your changes. Maybe @mzeryck has an idea on this.

**Comment by mzeryck** [comment] 2020-12-23 19:12
@d3vcoder This is an older version of Weather Cal (the settings are now in a UITableView rather than the script). However, the code does attempt to check for older versions. Can you please go into the Weather Cal code script, and find this section:
```javascript
// Determine if we're using the old or new setup.
if (typeof layout == "object") {
  this.settings = layout

} else {
  this.settings = this.getSettings()
  this.settings.layout = layout
}
```
And then add a single line of code after it:
`console.log(this.settings)`

Can you let me know what it shows? It should display a readout of all the settings from the main script file.

**Comment by d3vcoder** [comment] 2020-12-23 21:27
I’ll paste below the output of the log. 

2020-12-23 16:26:02: {"widget":{"locale":"","units":"imperial","preview":"large","padding":5,"tintIcons":false},"layout":"\n  \n  row\n    column(200)\n      greeting\n      date \n      sunset\n      battery\n    \n    column\n      center\n      current \n      future\n      \n  \n  space()\n  \n  row\n    \n    column\n      left\n      events\n      \n    column\n      reminders\n  ","localization":{"nightGreeting":"Good night.","morningGreeting":"Good morning.","afternoonGreeting":"Good afternoon.","eveningGreeting":"Good evening.","nextHourLabel":"Next hour","tomorrowLabel":"Tomorrow","noEventMessage":"No more events","durationMinute":"m","durationHour":"h","covid":"{cases} cases, {deaths} deaths, {recovered} recoveries"},"date":{"dynamicDateSize":false,"staticDateSize":"large","smallDateFormat":"EEEE, MMMM d","largeDateLineOne":"d","largeDateLineTwo":"EEEE"},"events":{"numberOfEvents":3,"minutesAfter":5,"showAllDay":true,"showTomorrow":20,"showEventLength":"duration","selectCalendars":[],"showCalendarColor":"rectangle left","noEventBehavior":"message"},"reminders":{"numberOfReminders":3,"useRelativeDueDate":false,"showWithoutDueDate":false,"showOverdue":true,"todayOnly":true,"selectLists":[],"showListColor":"rectangle left"},"sunrise":{"showWithin":0,"separateElements":false},"weather":{"showLocation":false,"horizontalCondition":true,"showCondition":false,"showHighLow":true,"showRain":true,"tomorrowShownAtHour":20,"showDays":4,"showDaysFormat":"E","showToday":false},"covid":{"country":"USA","url":"https://covid19.who.int"},"font":{"defaultText":{"size":14,"color":"ffffff","font":"regular"},"smallDate":{"size":17,"color":"","font":"semibold"},"largeDate1":{"size":50,"color":"","font":"light"},"largeDate2":{"size":20,"color":"","font":"light"},"greeting":{"size":20,"color":"","font":"light"},"eventLabel":{"size":14,"color":"","font":"semibold"},"eventTitle":{"size":14,"color":"","font":"semibold"},"eventTime":{"size":14,"color":"ffffffcc","font":""},"noEvents":{"size":15,"color":"","font":"semibold"},"largeTemp":{"size":30,"color":"","font":"light"},"smallTemp":{"size":14,"color":"","font":""},"tinyTemp":{"size":12,"color":"","font":""},"customText":{"size":14,"color":"","font":""},"battery":{"size":14,"color":"","font":"medium"},"sunrise":{"size":14,"color":"","font":"medium"},"covid":{"size":14,"color":"","font":"medium"}}}

**Comment by mzeryck** [comment] 2020-12-24 01:13
@d3vcoder Ah, found the bug! It's fixed in the most recent version, if you delete and re-download the Weather Cal code script.

**Closed** 2022-03-14 18:52 UTC
Labels: Fixed
